### ISSUE TITLE
Unix support?

### ISSUE THREAD

**Issue by l0oky** [RickCHodgin/libsf#38]
Hi, been following you on Universal Thread from time to time. Your project is quite large and ambitious, hope you finish it. 

Do you have any plans with Visual FreePro to support GNU compilers? So we can develop FreePro applications on Linux..?

**Comment by RickCHodgin** [comment]
Visual FreePro, Jr. currently compiles in 32-bit and 64-bit mode using MSVC and GCC 4.8.1 and later.  I haven't compiled it in a while, so it may not compile today, but it would only be due to regressions which would be easily fixed.  Also, the 64-bit compiled version will not launch.  I've never even bothered to investigate why as I'm sure it's some GCC quirk that I'm just not aware of, and because the 64-bit MSVC version does launch.

You can see versions with working GCC compiles here (from version 0.38 and later):
http://www.visual-freepro.org/vjr/indexmain.html

**Comment by RickCHodgin** [comment]
I began working on a Linux-to-Windows conversion, called lin2win, and got it mostly framed, and somewhat coded, but then I went on to another project:
https://github.com/RickCHodgin/libsf/tree/master/utils/common/cpp/lin2win

This would provide a Win32 API that emulates in an X environment.  I still plan to complete it as I plan to port VJr, and ultimately the full version VFrP (called just "Visual FreePro" without the ", Jr." part), to Linux and other *NIX/X-based environments.

Just takes time and help.  So far, it's been 99% me, and 1% Stefano D'Amico, and I've been very very very thankful for his support.  It would be nice to have more people involved helping out.

**Comment by l0oky** [comment]
Looks like I've made a silly question then.. VJr already supports Linux for day one. I think I was confused when looking at the `.sln` files.

**Comment by l0oky** [comment]
I'm a bit lost on how to compile VJr with GCC. I'm running on Debian Jessie 8, CodeLite 6.1.1

I get this build output:
```
/bin/sh -c '/usr/bin/make -j4 -e -f  Makefile'
----------Building project:[ vjr - Debug ]----------
make[1]: Entering directory '/home/l0oky/Projects/cpp/src/github.com/rickchodgin/libsf/source/vjr/projects/linux_gcc_codelite'
/usr/bin/g++   -c  "/home/l0oky/Projects/cpp/src/github.com/rickchodgin/libsf/source/vjr/source/bmps/bmps.cpp" -g -O0 -Wall -Wno-comment -Wno-multichar -Wno-narrowing -Wno-write-strings -Wno-format-contains-nul  -o ./Debug/bmps_bmps.cpp.o -I. -I.
/home/l0oky/Projects/cpp/src/github.com/rickchodgin/libsf/source/vjr/source/bmps/bmps.cpp:91:51: fatal error: /libsf/utils/common/cpp/common_types.h: No such file or directory
  #include "/libsf/utils/common/cpp/common_types.h"
                                                   ^
compilation terminated.
vjr.mk:99: recipe for target 'Debug/bmps_bmps.cpp.o' failed
make[1]: *** [Debug/bmps_bmps.cpp.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/l0oky/Projects/cpp/src/github.com/rickchodgin/libsf/source/vjr/projects/linux_gcc_codelite'
Makefile:4: recipe for target 'All' failed
make: *** [All] Error 2
2 errors, 0 warnings
```

**Comment by RickCHodgin** [comment]
VJr is designed to compile using GCC for Windows (MinGW, for example).  It's not designed to run on Linux today.  It needs the lin2win layer completed, and the appropriate .mak files created.

Sorry for the confusion.

**Comment by RickCHodgin** [comment]
Vjr exists at:
https://github.com/RickCHodgin/libsf/tree/master/source/vjr

VFrP exists at:
https://github.com/RickCHodgin/libsf/tree/master/source/vfrp/core

They are separate, but they share some common code.  In addition, they are completely separate projects that are not related.  The only things which they share are fundamental data types, structures, etc.  VFrP is also designed to work in a virtual machine, whereas VJr is designed to run natively in Windows.

LibSF was created to be a complete software solution, from kernel development to app development to other media and content.  The big project I'm working on is called the Village Freedom Project (which could be considered to be something like the GNU Project), and it is part of a large vision to create such a software repository as an offering unto my Lord and Savior, Jesus Christ, rather than just to offer it up for no reason.  We are explicitly creating an offering built upon our faith, upon our service to the Lord, giving back to Him and mankind the fruits of the gifts He first gave us.

Hope this helps.

**Comment by RickCHodgin** [comment]
If this helps, you can think of it this way.  I intend to create the \libsf\ parent directory which contains all source code offered up by LibSF.  In that way, everything you need to compile any project you have, will all be there.  No need to install additional packages or source code.

We are moving into the realm of multi-Terabyte hard drives, multi-core computers, multi-GB memory in our computers, high-speed always-on networking, etc.  LibSF's base design is going to take advantage of that baseline we're entering the playing field at.  Our goals will be on current equipment, and forward.

**Comment by l0oky** [comment]
Hope you find your efforts useful in the future. I was thinking If someone wants to contribute to one project I should clone only Its source and this common source. This way It's much easier for an open source developer to follow the code and eventually contribute. What people normally do on GitHub is create an organisation (`libsf` in this case) with many repositories (`common`, `VJr`, VFrP`, etc ...) which are just a piece of something larger, so instead of having to download/upload the whole stack at a time, a contributor only pushes commits one project at a time. 

If a compiler needs two repositories, then you could use git `submodules` feature. This way say `VJr 1.0` depends on `Common 1.0`. In current setting If you update `Common` source to `1.1`, `VJr 1.0` build may fail too. Using git submodules (in say `VJr` repo), you will update `Common`  submodule to `1.1`  only when `VJr` source code is ready.

**Comment by RickCHodgin** [comment]
The way LibSF is setup, you download all our source code in one shot, open the project you desire, and compile.  No assembly of various libraries or packages.

Versions will be frozen on git branches.

Best regards,
Rick C. Hodgin

**Comment by jhernancanom** [comment]
Yes, Muhamed.

You can do what you are saying. Rick will say you what is the GitHub
repository for you to clone and contribute as you are saying.

My name is Hernán Cano, from Medellín, Antioquia, Colombia. I am a VFrP &
VJr Contributor. I am spanish forum admin and I can help you (not strictly
in C-programming, but possible), but testing and translating for spanish
community.

If you could try in Linux environment, it could be very helpful. For now,
Rick needs to make some adjustments in core for it could run in Windows
(when I say core I mean something that he calls "Exodus operating system"
and RDC (Rapid Development compiler).

Very pleasant you to be here.

*How can I contribute to VJr?*
http://www.visual-freepro.org/wiki/index.php/VXB#How_can_I_contribute_to_VJr.3F

*VXB - Visual FreePro, Jr's XBase Language*
http://www.visual-freepro.org/wiki/index.php/VXB

*Visual FreePro in English*
https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!forum/visual-freepro-in-english

*RDC (Rapid Development Compiler)*
https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!forum/rapid_development_compiler

Visual FreePro en Español
https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!forum/vfrp

**Comment by l0oky** [comment]
Thank you, I'll try to compile the project and open other issue If needed.
