### ISSUE TITLE
CLEAR command

### ISSUE THREAD

**Issue by damste** [RickCHodgin/libsf#4]
CLEAR command does not clean the entire display, a line remains visible :)

**Comment by RickCHodgin** [comment]
I noticed that.  I kind of like it actualy, but it's not supposed to be that way.

It was a bug I introduced when fixing the bug you found the other day when you delete the last character the system crashes.  I'll fix it later today.

If you want to give it a try, look in the sem.cpp source files for the delete.  You'll find a test if the current line is not the first line and last line (meaning it's not the only line).  If that test is passed, it deletes the line, otherwise it doesn't.  What it should do is if that test fails it should go ahead and delete the contents of that line, but not the line.  This can be done by setting the line->sourceCode_populatedLength value to 0.  Nothing actually has to be deleted.

Good catch! :-) LOL!  And ... I'm sorry. :-)

**Comment by RickCHodgin** [comment]
I think I'll add a CONTINUE option to CLEAR, which will leave the last line on there.

CLEAR CONTINUE [nCount]

It will continue by clearing everything except it will leave the last 1 lines (or nCount lines if nCount is provided).

For now I'll just fix the bug. :-)

Best regards,
Rick C. Hodgin

**Comment by RickCHodgin** [comment]
Fixed with https://github.com/RickCHodgin/libsf/commit/7f1da2bde98610f121cfeb9bd6f583030881f844

**Comment by RickCHodgin** [comment]
Fixed.  Renamed it CLEAR KEEP nLines.

https://github.com/RickCHodgin/libsf/commit/e89231dd14ce6aa20d48627b5df05d2cd5592bf8
